name: Checkstyle

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  checkstyle:
    name: Run Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '24'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run Checkstyle
        id: checkstyle
        run: |
          mvn checkstyle:check > checkstyle.log 2>&1 || true
          grep '\[ERROR\]' checkstyle.log | tail -n 20 > summary.log || echo "No violations found." > summary.log

          {
            echo 'summary<<EOF'
            cat summary.log | sed 's/%/%%/g'
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      - name: Upload full Checkstyle log
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-log
          path: checkstyle.log

      - name: Comment on Checkstyle failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: checkstyle
          body: |
            ⚠️ **Checkstyle found violations** in commit `${{ github.sha }}`

            🧪 Showing last 20 `[ERROR]` lines from Checkstyle output:

            ```
            ${{ steps.checkstyle.outputs.summary }}
            ```

            📦 [Download full checkstyle.log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

      - name: Comment on Checkstyle success
        if: success()
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: checkstyle
          body: |
            ✅ **Checkstyle passed successfully** for commit `${{ github.sha }}`

            📦 [View checkstyle log](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})